// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SgMsgId.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SgMsgId.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* NetMsgId_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_SgMsgId_2eproto() {
  protobuf_AddDesc_SgMsgId_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SgMsgId.proto");
  GOOGLE_CHECK(file != NULL);
  NetMsgId_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SgMsgId_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_SgMsgId_2eproto() {
}

void protobuf_AddDesc_SgMsgId_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rSgMsgId.proto*)\n\010NetMsgId\022\r\n\tCS_PbTest"
    "\020\001\022\016\n\nCS_UseItem\020\002", 58);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SgMsgId.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SgMsgId_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SgMsgId_2eproto {
  StaticDescriptorInitializer_SgMsgId_2eproto() {
    protobuf_AddDesc_SgMsgId_2eproto();
  }
} static_descriptor_initializer_SgMsgId_2eproto_;
const ::google::protobuf::EnumDescriptor* NetMsgId_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NetMsgId_descriptor_;
}
bool NetMsgId_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
