//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SgMsg.proto
namespace SgMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbTest")]
  public partial class PbTest : global::ProtoBuf.IExtensible
  {
    public PbTest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseItem")]
  public partial class UseItem : global::ProtoBuf.IExtensible
  {
    public UseItem() {}
    
    private int _useCommond;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"useCommond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int useCommond
    {
      get { return _useCommond; }
      set { _useCommond = value; }
    }
    private int _pktId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pktId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pktId
    {
      get { return _pktId; }
      set { _pktId = value; }
    }
    private int _itemIndex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"itemIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemIndex
    {
      get { return _itemIndex; }
      set { _itemIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}