//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SgMsgId.proto
namespace SgMsgId
{
    [global::ProtoBuf.ProtoContract(Name=@"NetMsgId")]
    public enum NetMsgId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_PbTest", Value=1)]
      CS_PbTest = 1
    }
  
}